import { useEffect, useState } from "react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  LabelList,
} from "recharts";
import Papa from "papaparse";
import "./App.css";

function App() {
  const [activeTab, setActiveTab] = useState("health");
  const [healthData, setHealthData] = useState([]);
  const [propertyData, setPropertyData] = useState([]);

  // --------------------------------------------------
  // Load CSV outputs generated by the PySpark pipeline
  // --------------------------------------------------

  useEffect(() => {
    Papa.parse("/results/q1_health_life_portfolio.csv", {
      download: true,
      header: true,
      dynamicTyping: true,
      complete: (results) => {
        setHealthData(
          results.data.filter((row) => row.product_code)
        );
      },
    });

    Papa.parse("/results/q2_property_casualty_portfolio.csv", {
      download: true,
      header: true,
      dynamicTyping: true,
      complete: (results) => {
        setPropertyData(
          results.data.filter((row) => row.product_code)
        );
      },
    });
  }, []);

  // --------------------------------------------------
  // Select active portfolio
  // --------------------------------------------------

  const data =
    activeTab === "health"
      ? healthData
      : propertyData;

  // --------------------------------------------------
  // Portfolio KPIs
  // --------------------------------------------------

  const totalClaims = data.reduce(
    (sum, row) => sum + (row.claim_count || 0),
    0
  );

  const totalClaimAmount = data.reduce(
    (sum, row) => sum + (row.total_claim_amount || 0),
    0
  );

  const averageClaim =
    totalClaims > 0
      ? totalClaimAmount / totalClaims
      : 0;

  const totalApproved = data.reduce(
    (sum, row) => sum + (row.approved_claims || 0),
    0
  );

  const approvalRate =
    totalClaims > 0
      ? (totalApproved / totalClaims) * 100
      : 0;

  // --------------------------------------------------
  // Claims and claim amount by country
  // --------------------------------------------------

  const countryData = Object.values(
    data.reduce((acc, row) => {
      const country = row.claim_country;

      if (!acc[country]) {
        acc[country] = {
          country,
          claims: 0,
          claimAmount: 0,
        };
      }

      acc[country].claims += row.claim_count || 0;

      acc[country].claimAmount +=
        row.total_claim_amount || 0;

      return acc;
    }, {})
  ).sort((a, b) => b.claims - a.claims);

  // --------------------------------------------------
  // Claims by customer tier / risk category
  // --------------------------------------------------

  const categoryData = Object.values(
    data.reduce((acc, row) => {
      const category =
        activeTab === "health"
          ? row.customer_tier
          : row.risk_category;

      if (!acc[category]) {
        acc[category] = {
          category,
          claims: 0,
        };
      }

      acc[category].claims +=
        row.claim_count || 0;

      return acc;
    }, {})
  ).sort((a, b) => b.claims - a.claims);

  // --------------------------------------------------
  // Approval rate by customer tier / risk category
  // --------------------------------------------------

  const approvalData = Object.values(
    data.reduce((acc, row) => {
      const category =
        activeTab === "health"
          ? row.customer_tier
          : row.risk_category;

      if (!acc[category]) {
        acc[category] = {
          category,
          approved: 0,
          claims: 0,
        };
      }

      acc[category].approved +=
        row.approved_claims || 0;

      acc[category].claims +=
        row.claim_count || 0;

      return acc;
    }, {})
  ).map((item) => ({
    category: item.category,
    approvalRate:
      item.claims > 0
        ? Number(
            (
              (item.approved / item.claims) *
              100
            ).toFixed(2)
          )
        : 0,
  }));

  // --------------------------------------------------
  // Table header formatting
  // --------------------------------------------------

  const formatHeader = (column) => {
    return column
      .replaceAll("_", " ")
      .replace(/\b\w/g, (letter) =>
        letter.toUpperCase()
      );
  };

  // --------------------------------------------------
  // Currency formatting
  // --------------------------------------------------

  const monetaryColumns = [
    "total_claim_amount",
    "average_claim_amount",
    "avg_premium",
    "estimated_premium",
    "estimated_commission",
  ];

  // --------------------------------------------------
  // Render dashboard
  // --------------------------------------------------

  return (
    <div className="app">

      {/* Header */}

      <header className="header">

        <div className="header-brand">

          <h1>Insurance Analytics</h1>

          <p>
            Claims Portfolio Intelligence
            <span className="separator">•</span>
            Currency: USD
          </p>

        </div>

        <div className="tabs">

          <button
            className={
              activeTab === "health"
                ? "active"
                : ""
            }
            onClick={() =>
              setActiveTab("health")
            }
          >
            Health & Life
          </button>

          <button
            className={
              activeTab === "property"
                ? "active"
                : ""
            }
            onClick={() =>
              setActiveTab("property")
            }
          >
            Property & Casualty
          </button>

        </div>

      </header>

      <main>

        {/* Portfolio Title */}

        <section className="hero">

          <h2>
            {activeTab === "health"
              ? "Health & Life Portfolio"
              : "Property & Casualty Portfolio"}
          </h2>

          <p>
            {data.length} analytical records loaded
            from the PySpark output.
          </p>

        </section>

        {/* KPI Cards */}

        <section className="kpi-grid">

          <div className="kpi-card">

            <span>Total Claims</span>

            <strong>
              {totalClaims.toLocaleString()}
            </strong>

          </div>

          <div className="kpi-card">

            <span>Total Claim Amount</span>

            <strong>
              $
              {(totalClaimAmount / 1000000000).toFixed(
                2
              )}
              B
            </strong>

          </div>

          <div className="kpi-card">

            <span>Average Claim</span>

            <strong>
              $
              {averageClaim.toLocaleString(
                undefined,
                {
                  maximumFractionDigits: 0,
                }
              )}
            </strong>

          </div>

          <div className="kpi-card">

            <span>Approval Rate</span>

            <strong>
              {approvalRate.toFixed(2)}%
            </strong>

          </div>

        </section>

        {/* Country Charts */}

        <section className="chart-grid">

          {/* Claims by Country */}

          <div className="table-card">

            <div className="table-header">

              <h3>
                Claims by Country
              </h3>

              <span>
                Claim Volume
              </span>

            </div>

            <div className="chart-container">

              <ResponsiveContainer
                width="100%"
                height="100%"
              >

                <BarChart
                  data={countryData}
                  layout="vertical"
                  margin={{
                    left: 10,
                    right: 55,
                    top: 10,
                    bottom: 10,
                  }}
                >

                  <CartesianGrid
                    strokeDasharray="3 3"
                  />

                  <XAxis
                    type="number"
                    tick={{
                      fontSize: 11,
                    }}
                  />

                  <YAxis
                    type="category"
                    dataKey="country"
                    width={38}
                    tick={{
                      fontSize: 11,
                    }}
                  />

                  <Tooltip />

                  <Bar
                    dataKey="claims"
                    name="Claims"
                    fill="#38bdf8"
                    barSize={14}
                    radius={[0, 4, 4, 0]}
                  >
                    <LabelList
                      dataKey="claims"
                      position="right"
                      formatter={(value) =>
                        Number(value).toLocaleString()
                      }
                      style={{
                        fontSize: 11,
                        fontWeight: 600,
                      }}
                    />
                  </Bar>

                </BarChart>

              </ResponsiveContainer>

            </div>

          </div>

          {/* Claim Amount by Country */}

          <div className="table-card">

            <div className="table-header">

              <h3>
                Claim Amount by Country
              </h3>

              <span>
                USD
              </span>

            </div>

            <div className="chart-container">

              <ResponsiveContainer
                width="100%"
                height="100%"
              >

                <BarChart
                  data={countryData}
                  layout="vertical"
                  margin={{
                    left: 10,
                    right: 75,
                    top: 10,
                    bottom: 10,
                  }}
                >

                  <CartesianGrid
                    strokeDasharray="3 3"
                  />

                  <XAxis
                    type="number"
                    tick={{
                      fontSize: 11,
                    }}
                    tickFormatter={(value) =>
                      `$${(
                        value / 1000000
                      ).toFixed(0)}M`
                    }
                  />

                  <YAxis
                    type="category"
                    dataKey="country"
                    width={38}
                    tick={{
                      fontSize: 11,
                    }}
                  />

                  <Tooltip
                    formatter={(value) =>
                      `$${Number(
                        value
                      ).toLocaleString()}`
                    }
                  />

                  <Bar
                    dataKey="claimAmount"
                    name="Claim Amount"
                    fill="#38bdf8"
                    barSize={14}
                    radius={[0, 4, 4, 0]}
                  >
                    <LabelList
                      dataKey="claimAmount"
                      position="right"
                      formatter={(value) =>
                        `$${(
                          Number(value) /
                          1000000
                        ).toFixed(1)}M`
                      }
                      style={{
                        fontSize: 10,
                        fontWeight: 600,
                      }}
                    />
                  </Bar>

                </BarChart>

              </ResponsiveContainer>

            </div>

          </div>

        </section>

        {/* Category Charts */}

        <section className="chart-grid">

          {/* Claims by Tier / Risk */}

          <div className="table-card">

            <div className="table-header">

              <h3>
                Claims by{" "}
                {activeTab === "health"
                  ? "Customer Tier"
                  : "Risk Category"}
              </h3>

              <span>
                Claim Volume
              </span>

            </div>

            <div className="chart-container">

              <ResponsiveContainer
                width="100%"
                height="100%"
              >

                <BarChart
                  data={categoryData}
                  margin={{
                    top: 15,
                    right: 35,
                    left: 10,
                    bottom: 5,
                  }}
                >

                  <CartesianGrid
                    strokeDasharray="3 3"
                  />

                  <XAxis
                    dataKey="category"
                    tick={{
                      fontSize: 11,
                    }}
                  />

                  <YAxis
                    tick={{
                      fontSize: 11,
                    }}
                  />

                  <Tooltip />

                  <Bar
                    dataKey="claims"
                    name="Claims"
                    fill="#38bdf8"
                    barSize={24}
                    radius={[4, 4, 0, 0]}
                  >
                    <LabelList
                      dataKey="claims"
                      position="top"
                      formatter={(value) =>
                        Number(value).toLocaleString()
                      }
                      style={{
                        fontSize: 10,
                        fontWeight: 600,
                      }}
                    />
                  </Bar>

                </BarChart>

              </ResponsiveContainer>

            </div>

          </div>

          {/* Approval Rate */}

          <div className="table-card">

            <div className="table-header">

              <h3>
                Approval Rate by{" "}
                {activeTab === "health"
                  ? "Customer Tier"
                  : "Risk Category"}
              </h3>

              <span>
                Percentage
              </span>

            </div>

            <div className="chart-container">

              <ResponsiveContainer
                width="100%"
                height="100%"
              >

                <BarChart
                  data={approvalData}
                  margin={{
                    top: 15,
                    right: 35,
                    left: 10,
                    bottom: 5,
                  }}
                >

                  <CartesianGrid
                    strokeDasharray="3 3"
                  />

                  <XAxis
                    dataKey="category"
                    tick={{
                      fontSize: 11,
                    }}
                  />

                  <YAxis
                    domain={[0, 100]}
                    tick={{
                      fontSize: 11,
                    }}
                    tickFormatter={(value) =>
                      `${value}%`
                    }
                  />

                  <Tooltip
                    formatter={(value) =>
                      `${value}%`
                    }
                  />

                  <Bar
                    dataKey="approvalRate"
                    name="Approval Rate"
                    fill="#0284c7"
                    barSize={24}
                    radius={[4, 4, 0, 0]}
                  >
                    <LabelList
                      dataKey="approvalRate"
                      position="top"
                      formatter={(value) =>
                        `${value}%`
                      }
                      style={{
                        fontSize: 10,
                        fontWeight: 600,
                      }}
                    />
                  </Bar>

                </BarChart>

              </ResponsiveContainer>

            </div>

          </div>

        </section>

        {/* Portfolio Results */}

        <section className="table-card">

          <div className="table-header">

            <h3>
              Portfolio Results
            </h3>

            <span>
              Source: PySpark Analytical Mart
            </span>

          </div>

          <div className="table-wrapper">

            <table>

              <thead>

                <tr>

                  {data.length > 0 &&
                    Object.keys(data[0]).map(
                      (column) => (
                        <th key={column}>
                          {formatHeader(column)}
                        </th>
                      )
                    )}

                </tr>

              </thead>

              <tbody>

                {data
                  .slice(0, 20)
                  .map((row, index) => (

                    <tr key={index}>

                      {Object.entries(row).map(
                        ([column, value]) => (

                          <td key={column}>

                            {typeof value ===
                            "number"
                              ? monetaryColumns.includes(
                                  column
                                )
                                ? `$${value.toLocaleString(
                                    undefined,
                                    {
                                      maximumFractionDigits: 2,
                                    }
                                  )}`
                                : value.toLocaleString(
                                    undefined,
                                    {
                                      maximumFractionDigits: 2,
                                    }
                                  )
                              : value}

                          </td>

                        )
                      )}

                    </tr>

                  ))}

              </tbody>

            </table>

          </div>

        </section>

      </main>

    </div>
  );
}

export default App;